"""Initial migration

Revision ID: 07ac655f312e
Revises: 3e576a9ed8ad
Create Date: 2025-04-28 14:34:04.488375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07ac655f312e'
down_revision: Union[str, None] = '3e576a9ed8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('대화 아이디', sa.Integer(), nullable=False),
    sa.Column('세션 아이디', sa.String(length=50), nullable=True),
    sa.Column('대화 시각', sa.TIMESTAMP(), nullable=True),
    sa.Column('질문', sa.String(length=250), nullable=True),
    sa.Column('대답', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('대화 아이디')
    )
    op.create_index(op.f('ix_conversation_대화 아이디'), 'conversation', ['대화 아이디'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_대화 아이디'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
