"""Create LLM table

Revision ID: 1306c12629d1
Revises: ad7b6223ba8e
Create Date: 2025-05-12 22:30:34.210101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1306c12629d1'
down_revision: Union[str, None] = 'ad7b6223ba8e'  # 이제 첫 번째 마이그레이션을 가리킵니다
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 기존 테이블 이름을 'conversation'에서 'Conversation'으로 변경 (필요한 경우)
    op.rename_table('conversation', 'Conversation')
    
    # 인덱스 이름 변경
    op.drop_index('ix_conversation_conversation_id', table_name='Conversation')
    op.create_index(op.f('ix_Conversation_conversation_id'), 'Conversation', ['conversation_id'], unique=False)
    
    # 새로운 LLM 테이블 생성
    op.create_table('LLM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LLM')
    
    # 원래 이름으로 다시 변경
    op.drop_index('ix_Conversation_conversation_id', table_name='Conversation')
    op.rename_table('Conversation', 'conversation')
    op.create_index(op.f('ix_conversation_conversation_id'), 'conversation', ['conversation_id'], unique=False)
    # ### end Alembic commands ###