"""Create LLM table

Revision ID: 1306c12629d1
Revises: 
Create Date: 2025-05-12 22:30:34.210101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1306c12629d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversation',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('query', sa.String(length=250), nullable=True),
    sa.Column('answer', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_Conversation_conversation_id'), 'Conversation', ['conversation_id'], unique=False)
    op.create_table('LLM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LLM')
    op.drop_index(op.f('ix_Conversation_conversation_id'), table_name='Conversation')
    op.drop_table('Conversation')
    # ### end Alembic commands ###
