"""Initial migration

Revision ID: 3e576a9ed8ad
Revises: 48266eecf9bd
Create Date: 2025-04-28 14:28:43.861342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e576a9ed8ad'
down_revision: Union[str, None] = '48266eecf9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('세션 아이디', sa.String(length=50), nullable=True))
    op.alter_column('conversation', '대화 아이디',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', '대화 아이디',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('conversation', '세션 아이디')
    # ### end Alembic commands ###
