"""session_id col 추가

Revision ID: 54fa55e977fe
Revises: 07ac655f312e
Create Date: 2025-04-29 13:12:40.544310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54fa55e977fe'
down_revision: Union[str, None] = '07ac655f312e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.add_column('conversation', sa.Column('session_id', sa.String(length=50), nullable=True))
    op.add_column('conversation', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('conversation', sa.Column('query', sa.String(length=250), nullable=True))
    op.add_column('conversation', sa.Column('answer', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_conversation_대화 아이디', table_name='conversation')
    op.create_index(op.f('ix_conversation_conversation_id'), 'conversation', ['conversation_id'], unique=False)
    op.drop_column('conversation', '질문')
    op.drop_column('conversation', '대화 시각')
    op.drop_column('conversation', '세션 아이디')
    op.drop_column('conversation', '대화 아이디')
    op.drop_column('conversation', '대답')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('대답', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('대화 아이디', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('conversation', sa.Column('세션 아이디', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('대화 시각', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('질문', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conversation_conversation_id'), table_name='conversation')
    op.create_index('ix_conversation_대화 아이디', 'conversation', ['대화 아이디'], unique=False)
    op.drop_column('conversation', 'answer')
    op.drop_column('conversation', 'query')
    op.drop_column('conversation', 'created_at')
    op.drop_column('conversation', 'session_id')
    op.drop_column('conversation', 'conversation_id')
    # ### end Alembic commands ###
